/**
 * Seed script — run with:  npm run db:seed
 *
 * Creates:
 *   - 1 demo business ("Demo Café")
 *   - 1 API key (raw key printed once)
 *   - 4 sample customers
 *   - 6 sample orders
 *   - 6 sample review requests in various states
 *
 * Only run in dev/staging. Never in production.
 */

// Must load env BEFORE any other imports (ESM hoisting)
import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd());

async function main() {
  const { createHash, randomBytes } = await import("node:crypto");
  const { db } = await import("./index.js");
  const { businesses, apiKeys, customers, orders, reviewRequests } =
    await import("./schema.js");

  function sha256Hex(value: string): string {
    return createHash("sha256").update(value).digest("hex");
  }

  function generateApiKey(): string {
    const raw = randomBytes(32).toString("base64url");
    return `rqk_${raw}`;
  }

  console.log("Seeding database...\n");

  // 1. Business
  const [biz] = await db
    .insert(businesses)
    .values({
      name: "Demo Café",
      slug: "demo",
      googleReviewUrl:
        "https://search.google.com/local/writereview?placeid=DEMO_PLACE_ID",
    })
    .onConflictDoNothing()
    .returning();

  if (!biz) {
    console.log("Business 'demo' already exists — skipping seed.");
    return;
  }
  console.log(`Created business: ${biz.name} (${biz.id})`);

  // 2. API key
  const rawKey = generateApiKey();
  const keyHash = sha256Hex(rawKey);
  const prefix = rawKey.slice(0, 8);

  await db.insert(apiKeys).values({
    businessId: biz.id,
    name: "Development",
    prefix,
    keyHash,
    status: "active",
  });

  console.log("\nAPI key created (shown once — save it now):");
  console.log(`  ${rawKey}\n`);

  // Persist to .dev-keys for easy reference
  const { appendFileSync, existsSync } = await import("node:fs");
  const { join } = await import("node:path");
  const keysPath = join(process.cwd(), ".dev-keys");
  const line = `DEMO_API_KEY=${rawKey}\n`;
  if (existsSync(keysPath)) {
    appendFileSync(keysPath, line, "utf-8");
  } else {
    appendFileSync(keysPath, `# Development seed keys — DO NOT COMMIT\n# Generated by: npm run db:seed\n\n${line}`, "utf-8");
  }
  console.log(`Key saved to .dev-keys\n`);

  // 3. Customers
  const customerData = [
    { name: "Angela", email: "angela@example.com" },
    { name: "Brian", email: "brian@example.com" },
    { name: "Claire", email: "claire@example.com" },
    { name: "Derek", email: "derek@example.com" },
  ];

  const custIds: string[] = [];
  for (const c of customerData) {
    const [row] = await db
      .insert(customers)
      .values({ businessId: biz.id, name: c.name, email: c.email })
      .returning({ id: customers.id });
    custIds.push(row.id);
  }
  console.log(`Created ${custIds.length} customers`);

  // 4. Orders
  const orderData = [
    { customerId: custIds[0], extId: "ORD-1001", daysAgo: 20 },
    { customerId: custIds[0], extId: "ORD-1002", daysAgo: 5 },
    { customerId: custIds[1], extId: "ORD-1003", daysAgo: 15 },
    { customerId: custIds[2], extId: "ORD-1004", daysAgo: 8 },
    { customerId: custIds[3], extId: "ORD-1005", daysAgo: 3 },
    { customerId: custIds[3], extId: "ORD-1006", daysAgo: 1 },
  ];

  const orderIds: string[] = [];
  for (const o of orderData) {
    const orderDate = new Date();
    orderDate.setDate(orderDate.getDate() - o.daysAgo);
    const [row] = await db
      .insert(orders)
      .values({
        businessId: biz.id,
        customerId: o.customerId,
        externalOrderId: o.extId,
        orderDate,
        metadata: { currency: "USD" },
      })
      .returning({ id: orders.id });
    orderIds.push(row.id);
  }
  console.log(`Created ${orderIds.length} orders`);

  // 5. Review requests in various states
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;

  const requests = [
    // Pending — no rating yet
    { orderId: orderIds[0], customerId: custIds[0], daysAgo: 18 },
    { orderId: orderIds[1], customerId: custIds[0], daysAgo: 3 },
    // Rated — no feedback
    { orderId: orderIds[2], customerId: custIds[1], daysAgo: 13, rating: 5 },
    { orderId: orderIds[3], customerId: custIds[2], daysAgo: 6, rating: 4 },
    // Completed — rated + feedback
    {
      orderId: orderIds[4],
      customerId: custIds[3],
      daysAgo: 2,
      rating: 3,
      feedback: "Coffee was great but the wait was a bit long.",
    },
    {
      orderId: orderIds[5],
      customerId: custIds[3],
      daysAgo: 1,
      rating: 5,
      feedback: "Absolutely love this place!",
    },
  ];

  for (const r of requests) {
    const token = randomBytes(32).toString("base64url");
    const tokenHash = sha256Hex(token);
    const createdAt = new Date(now - r.daysAgo * day);
    const expiresAt = new Date(now + (30 - r.daysAgo) * day);

    await db.insert(reviewRequests).values({
      businessId: biz.id,
      customerId: r.customerId,
      orderId: r.orderId,
      tokenHash,
      expiresAt,
      createdAt,
      updatedAt: createdAt,
      rating: r.rating ?? null,
      feedback: r.feedback ?? null,
      ratingSubmittedAt: r.rating
        ? new Date(now - (r.daysAgo - 1) * day)
        : null,
      feedbackSubmittedAt: r.feedback
        ? new Date(now - (r.daysAgo - 1) * day)
        : null,
      emailSentAt: createdAt,
      googleReviewClickCount:
        r.rating && r.rating >= 4 ? Math.floor(Math.random() * 3) : 0,
      googleReviewClickedAt:
        r.rating && r.rating >= 4
          ? new Date(now - (r.daysAgo - 1) * day)
          : null,
    });
  }
  console.log(`Created ${requests.length} review requests`);

  console.log("\nSeed complete!");
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
